// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtYjJjq2cLCqpLssmmstQwOAP97WN4vpE',
    appId: '1:1003582676731:web:b1fe942b8b1900cce71a5e',
    messagingSenderId: '1003582676731',
    projectId: 'oh-ootd-7f530',
    authDomain: 'oh-ootd-7f530.firebaseapp.com',
    storageBucket: 'oh-ootd-7f530.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlMvc2UQUKggqYZiWl2JemT9VXnhg8Wz0',
    appId: '1:1003582676731:android:26ea459f2a34387de71a5e',
    messagingSenderId: '1003582676731',
    projectId: 'oh-ootd-7f530',
    storageBucket: 'oh-ootd-7f530.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0wRd5ZYTNzIbpHRULVoUxTySuudsrgtQ',
    appId: '1:1003582676731:ios:22327a98a53ee766e71a5e',
    messagingSenderId: '1003582676731',
    projectId: 'oh-ootd-7f530',
    storageBucket: 'oh-ootd-7f530.appspot.com',
    iosClientId: '1003582676731-r1p8fkq41ntpsuej28nmb8hut8rvr0dj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ootd',
  );
}
